name: Current Event
description: Write about a current event

body:
  - type: markdown
    attributes:
      value: |
        #### Name of the news or media article where it was found, name of the article, and author
  
  - type: dropdown
    id: topic
    attributes:
      label: Check off the one you will be doing
      options:
        - "Local: This should be about something going on in Massachusetts" 
        - "National: This should be about something going on in the United States"
        - "International: This should be about something going on in another country"
        - "Politcal: This should be about something going on in the US politcal scene"
        - "Economic: This should be something going on in the U.S. economy"
    validations:
      required: true
  - type: input
    id: why
    attributes:
      label: Why do you think this?
      placeholder: ex. New York Times
    validations:
      required: true

  - type: input
    id: source
    attributes:
      label: Source
      description: Source of the article
      placeholder: ex. New York Times
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Title
      description: Title of the article
      placeholder: ex. Russia Censors Internet
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Author
      description: Author of the article
      placeholder: ex. John Appleseed
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link
      description: Link of the article
      placeholder: ex. https://nytimes.com/example_article.html
    validations:
      required: true



  - type: textarea
    id: summary
    attributes:
      label: Write a 6-8 sentence summary that includes the main idea of the article
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: audience
    attributes:
      label: Who was this article written for? Why do you think this?
    validations:
      required: true
  - type: textarea
    id: accomplish
    attributes:
      label: What was this article trying to accomplish?
    validations:
      required: true
  - type: textarea
    id: reaction-opinion
    attributes:
      label: What is your reaction to this article? What is your opinion of this situation after reading the article?
    validations:
      required: true
  - type: textarea
    id: impact-me
    attributes:
      label: How does this topic impact you? Explain!
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Take some notes and come up with talking points for when you need to share
    validations:
      required: true
  - type: textarea
    id: notes_from_classmates 
    attributes:
      label: Notes from classmates
      value: |
        #### Notes from _________
        - 
        - 
        - 
        - 
        - 
        - 
        #### Notes from _________
        - 
        - 
        - 
        - 
        - 
        - 



